name: walletapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  barcode_scan: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/car_service_icon.png
    - images/coffee_icon.png
    - images/credit_icon.png
    - images/debit_icon.png
    - images/floating_icon.png
    - images/men_dp.png
    - images/movie_ticket_icon.png
    - images/my_food.png
    - images/wallet_cover.png
    - images/zara.png
    - images/hamberg.png
    - images/curve_top.png
    - images/rounded_rect.png
    - images/rounded_rect_blue.png
    - images/currency.png
    - images/barcode_box.png
    - images/dummy_barcode.png
    - images/scanner_start.png
    - images/rounded_side.png
    - images/back_icon.png
    - images/blue_rect.png
    - images/drinks.png
    - images/border_rect.png
    - images/profile_curve.png
    - images/edit.png
    - images/profile_rect.png
    - images/change_pass_icon.png
    - images/payments.png
    - images/account.png
    - images/circle_black.png
    - images/right_arrow.png
    - images/credit_card.png
    - images/add_card.png
    - images/right_circle.png
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/ibmplexsans_light.ttf

    - family: IBMPlexSansMedium
      fonts:
        - asset: fonts/ibmplexsans_medium.ttf

    - family: IBMPlexSansSemiBold
      fonts:
        - asset: fonts/ibmplexsans_semibold.ttf


    - family: GilroyBold
      fonts:
        - asset: fonts/gilroy_bold.otf

    - family: GilroySemiBold
      fonts:
        - asset: fonts/gilroy_semibold.otf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
